### ISSUE TITLE
No browser-only API available

### ISSUE THREAD

**Issue by vtbassmatt** [vtbassmatt/responsivewit#1]
It looks like VSO has no way to make a purely browser-based client (for instance, using JSONP responses) to work around cross-origin restrictions. We'll need a service-side component to either directly proxy requests (serving both API and HTML from the same origin) or make all the calls and render the HTML. @phecdalouie @yiweiang @dogert any thoughts on architecture?

**Comment by vtbassmatt** [comment]
Actually, this might work after all. In a curl request, I noticed that we set Access-Control-Allow-Origin to *, so CORS might let this happen.

**Comment by yiweiang** [comment]
Yea, I've tried working on getting to the API using JS, but I haven't had
much success getting actual results back.... Also had to turn off CORS on
chrome.

On Wed, Jun 24, 2015 at 9:11 AM, Matt Cooper notifications@github.com
wrote:

> Actually, this might work after all. In a curl request, I noticed that we
> set Access-Control-Allow-Origin to *, so CORS might let this happen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vtbassmatt/responsivewit/issues/1#issuecomment-114927661
> .

## 

_Yi-Wei Ang_

T: (425) 229-1020
E: yiweiang@gmail.com
W: http://www.linkedin.com/in/yiweiang | http://www.yiweiang.net/
http://www.yiweiang.net/?utm_source=gmail&utm_medium=email&utm_campaign=direct

**Comment by vtbassmatt** [comment]
I got a CORS request to go through successfully. It immediately 302s, which
JQuery treats as an error so I need to handle it.

**Comment by vtbassmatt** [comment]
The 302 was an auth error, but after switching to alternative credentials I got this working. Hooray!
